name: Scribe
version: '${project.version}'
main: com.github.tonbei.scribe.Scribe
api-version: 1.17
authors: [ tonbei10 ]
description: Remove enchantments

commands:
  scribe:
    permission: scribe.admin

permissions:
  scribe.use:
    description: Allows players to use Scribe.
    default: true
  scribe.admin:
    description: Allows player to reload Scribe's config file.
    default: op